#!/usr/bin/env python

from __future__ import print_function

import os
import sys
import argparse
try:
    from pipes import quote
except ImportError:
    from shlex import quote

prog = os.path.basename(sys.argv[0])
sys.argv[0] = prog

mockbin_log = os.environ.get('MOCKBIN_LOG', None)

if mockbin_log:
    with open(mockbin_log, 'a') as logfile:
        logline = ' '.join([quote(entry) for entry in sys.argv])
        logfile.write("%s\n" % (logline))

if prog == 'tito':
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers()
    parser_release = subparsers.add_parser('release')
    parser_release.add_argument('dest')
    parser_release.add_argument('--scratch', action='store_true')
    parser_release.add_argument('--test', action='store_true')
    parser_release.add_argument('-y', action='store_true')
    parser_release.add_argument('--arg')
    parser_build = subparsers.add_parser('build')
    parser_build.add_argument('--srpm', action='store_const', dest='output', const='Wrote: hello.src.rpm')
    parser_build.add_argument('--scl', action='store')
    parser_build.add_argument('--offline', action='store_true')
    args = parser.parse_args()
    if 'output' in args and args.output:
        print(args.output)
